### PR TITLE
Add Jekyll formatting

### PR DESCRIPTION
**Pull request by daviddarnes**
Hi! Thanks a lot for making this tool! Found it very useful to export content from Medium blogs.

I thought the tool could benefit from being able to export content ready for Jekyll blogs. I've made the following changes:
- Listening for a `--jekyll` option
- Prefix all files with the date
- Place images all into a single `assets/images/` directory
- Wrap frontmatter string in double quotes to prevent build errors

Everything except the double quotes around frontmatter strings is all conditional with the `--jekyll` option.

It's not perfect, but I've tested it and it works a treat! Hope you appreciate this

### CODE REVIEW

**Comment by PatrickHeneise** [comment]
That looks great, thanks for the contribution! I'd love to add some tests to make sure this doesn't break the other output options, could you help with that?

**Comment by daviddarnes** [comment]
You're welcome! I think so, I had a quick snoop in the tests but couldn't see where you're testing the different options.

PS. Can the tool accept the JSON feed url as well as  the `/feed/@` RSS url? I've noticed that the feed url is limited to 8 posts and there's no way (that I can see) to switch pagination or limit

**Comment by PatrickHeneise** [comment]
There are no tests for the other options yet. It's a little complex with all the fs stuff happening.

Feeds *should* work, but I think pagination is missing. I tested only for individual URLs so far.

**Comment by daviddarnes** [comment]
Let me know how I should approach it the tests!

**Pull request merged**
